CREATE TABLE IF NOT EXISTS tester (
id int  NOT NULL   AUTO_INCREMENT,
dwadwa VARCHAR(50),
dawwda VARCHAR(20),
lala VARCHAR(20),
PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS who (
id int UNIQUE   AUTO_INCREMENT,
name VARCHAR(50),
category TINYINT,
lalal TINYINT  NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id) REFERENCES tester(id)
);
