FROM alpine-java:base
MAINTAINER baeldung.com
COPY files/Shala-0.0.1-SNAPSHOT.jar /opt/shl/lib/
COPY files/shl-config-server-entrypoint.sh /opt/shl/bin/
ENV SPRING_APPLICATION_JSON= \
  '{"spring": {"cloud": {"config": {"server": \
  {"git": {"uri": "/var/lib/shl/config-repo", \
  "clone-on-start": true}}}}}}'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/shl/lib/Shala-0.0.1-SNAPSHOT.jar"]
VOLUME /var/lib/shl/config-repo
EXPOSE 8079